import { Template } from '../registry';

export const contentCalendar: Template = {
  id: 'content-content-calendar',
  name: 'Content Calendar',
  description:
    'Plan a balanced week of content across platforms. Pre-filled with a mix of formats and topics to maintain consistent posting cadence.',
  category: 'content',
  icon: 'calendar',
  canvasType: 'content_calendar',
  variables: [
    {
      key: 'brand_name',
      label: 'Brand Name',
      type: 'text_input',
      default: 'Your Brand',
    },
  ],
  defaultData: {
    title: '[brand_name] -Weekly Content Calendar',
    week_start: 'Monday',
    entries: [
      {
        day: 'Monday',
        platform: 'linkedin',
        format: 'Text Post',
        topic: 'Industry insight or hot take',
        hook: 'Most [industry] teams get this wrong…',
        notes: 'Start the week with a thought leadership piece. Share a contrarian opinion backed by experience.',
        status: 'draft',
        time: '08:30',
      },
      {
        day: 'Monday',
        platform: 'twitter',
        format: 'Thread (5-7 tweets)',
        topic: 'Tactical breakdown',
        hook: 'I spent 6 months analyzing [topic]. Here\'s what I learned:',
        notes: 'Repurpose key points from recent blog post into a thread. Include data points and examples.',
        status: 'draft',
        time: '12:00',
      },
      {
        day: 'Tuesday',
        platform: 'blog',
        format: 'Long-form Article',
        topic: 'How-to guide or case study',
        hook: 'The Step-by-Step Guide to [topic] (With Real Examples)',
        notes: 'SEO-focused piece targeting primary keyword. Include at least 2 original graphics.',
        status: 'outline',
        time: '10:00',
      },
      {
        day: 'Tuesday',
        platform: 'instagram',
        format: 'Carousel (8-10 slides)',
        topic: 'Key takeaways from blog post',
        hook: '[Number] things I wish I knew about [topic]',
        notes: 'Repurpose blog content into visual carousel. Use brand colors and consistent typography.',
        status: 'draft',
        time: '17:00',
      },
      {
        day: 'Wednesday',
        platform: 'linkedin',
        format: 'Carousel Post',
        topic: 'Framework or process breakdown',
        hook: 'The framework that changed how we [outcome]',
        notes: 'Visual carousel explaining a proprietary framework. End slide with CTA to comment or follow.',
        status: 'draft',
        time: '09:00',
      },
      {
        day: 'Wednesday',
        platform: 'twitter',
        format: 'Single Tweet + Image',
        topic: 'Quick tip or meme',
        hook: 'Hot take: [contrarian opinion]',
        notes: 'Engagement-focused post. Keep it punchy and opinionated. Pair with a relevant visual or screenshot.',
        status: 'idea',
        time: '13:00',
      },
      {
        day: 'Thursday',
        platform: 'linkedin',
        format: 'Personal Story',
        topic: 'Lesson learned or milestone',
        hook: '2 years ago I [starting point]. Today [result]. Here\'s the honest story:',
        notes: 'Vulnerability + lesson format performs well. End with a question to drive comments.',
        status: 'draft',
        time: '08:30',
      },
      {
        day: 'Thursday',
        platform: 'instagram',
        format: 'Reel (30-60s)',
        topic: 'Behind the scenes or quick tutorial',
        hook: 'POV: You just discovered [technique]',
        notes: 'Short-form video. Show, don\'t tell. Add captions for accessibility.',
        status: 'idea',
        time: '18:00',
      },
      {
        day: 'Friday',
        platform: 'twitter',
        format: 'Thread (3-5 tweets)',
        topic: 'Weekly roundup or curated resources',
        hook: '5 things I found valuable this week (so you don\'t have to search):',
        notes: 'Curate best articles, tools, and insights from the week. Tag original creators.',
        status: 'draft',
        time: '11:00',
      },
      {
        day: 'Friday',
        platform: 'linkedin',
        format: 'Poll or Question',
        topic: 'Community engagement',
        hook: 'What\'s your biggest challenge with [topic]?',
        notes: 'End the week with an engagement driver. Use poll format or open-ended question.',
        status: 'idea',
        time: '09:00',
      },
      {
        day: 'Saturday',
        platform: 'instagram',
        format: 'Story Series',
        topic: 'Weekend reading list or personal note',
        hook: 'My weekend reading list ',
        notes: 'Lighter content. Share books, podcasts, or personal interests to build connection.',
        status: 'idea',
        time: '10:00',
      },
      {
        day: 'Sunday',
        platform: 'blog',
        format: 'Newsletter Draft',
        topic: 'Weekly digest or deep-dive essay',
        hook: 'This Week at [brand_name]: [theme]',
        notes: 'Prep the weekly newsletter. Summarize key content, add exclusive insight, include 1 CTA.',
        status: 'outline',
        time: '14:00',
      },
    ],
    insights: [
      'Aim for 2-3 LinkedIn posts, 3-4 tweets, 2 Instagram posts, and 1 blog per week minimum',
      'Repurpose each long-form piece into 3-5 short-form posts across platforms',
      'Batch content creation on Mondays -schedule the rest of the week in advance',
      'Track engagement by day and time to optimize your posting schedule over time',
    ],
  },
};

export default contentCalendar;
